routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('client/home', 'home')->middleware('auth:client');
Route::view('vendor/home', 'home')->middleware('auth:vendor');
Route::get('/', 'HomeController@showHome')->name('welcome');

Route::group(['prefix' => 'admin'], function () {
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::post('/logout', 'AdminAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'AdminAuth\RegisterController@register');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'vendor'], function () {
  Route::get('/login', 'VendorAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'VendorAuth\LoginController@login');
  Route::post('/logout', 'VendorAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'VendorAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'VendorAuth\RegisterController@register');

  Route::post('/password/email', 'VendorAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'VendorAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'VendorAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'VendorAuth\ResetPasswordController@showResetForm');

  Route::get('/order-delivered', 'DeliveryController@sendNotificationOnDelivery');

});

Route::group(['prefix' => 'client'], function () {
  Route::get('/login', 'ClientAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'ClientAuth\LoginController@login');
  Route::post('/logout', 'ClientAuth\LoginController@logout')->name('logout');

  Route::get('/register', 'ClientAuth\RegisterController@showRegistrationForm')->name('register');
  Route::post('/register', 'ClientAuth\RegisterController@register');

  Route::post('/password/email', 'ClientAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'ClientAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'ClientAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'ClientAuth\ResetPasswordController@showResetForm');

  Route::get('/settings', 'ClientSettingsController@showClientSettings')->name('settings');
  Route::get('/orders', 'ClientOrdersController@showClientOrders')->name('orders');
  Route::resource('/orders', 'ClientOrdersController')->only(['update']);
  Route::get('/cart', 'CartController@showCart')->name('cart');
  Route::get('/cart/add', 'CartController@addToCart');
  Route::get('/cart/remove', 'CartController@removeFromCart');
  Route::get('/cart/update', 'CartController@updateQuantity');
  Route::get('/payment', 'PaymentController@showPayment')->name('client.payment');
  Route::post('/payment/confirm_order', 'PaymentController@sendPayment')->name('client.confirm-order');
});

Route::resource('products', 'ProductController')->middleware('auth:vendor');
Route::resource('orders', 'OrderController')->middleware('auth:vendor');
Route::resource('vendor-edit', 'VendorController')->middleware('auth:vendor');
Route::resource('client-edit', 'ClientController')->middleware('auth:client');

app/Client.php
<?php

namespace App;

use App\Notifications\ClientResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Client extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ClientResetPassword($token));
    }

    public function orders()
    {
        return $this->hasMany('App\Order');
    }
}

// vim: set ts=4 sw=4 :

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Log;
use Storage;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $client = Client::find($id);

        $client_name = $request->input('client_name');
        $client_surname = $request->input('client_surname');
        $client_email = $request->input('client_email');

        $client_img = $request->input('newavatar');

        if ($client_name != ''){
            $client->name = $client_name;
        }

        if ($client_email != ''){
            $client->email = $client_email;
        }

        if ($request->hasFile('newavatar')){
            $file = $request->file('newavatar');
            $path = Storage::putFile('avatar', $file, 'public');
            if ($client->image != 'placeholders/imageprofile-placeholder-350x350.png') {
                Storage::delete($client->image);
            }
            $client->image = $path;
        }

        $client->save();
        return redirect()->route('settings');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

// vim: set ts=4 sw=4 :

resources/views/client/cart.blade.php
@extends('layouts.app')

@section('nav')
@include('includes.nav')
@endsection

@section('content')
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <div class="row">
      <div class="section no-pad-bot" id="index-banner">
        <div id="" class="col s12">
          <div class="row">
            <div class="col s12 l8">
              <h5 class="center">Il tuo carrello</h5>
              @forelse($cart_content as $elem)
              <div class="card-panel row" id="row-{{ $elem->id }}">
                  <div class="col s12 m4">{{ $elem->name }}</div>
                  <div class="col s3 m2">
                    <input placeholder="Quantità" name="qty" id="new_quantity_{{ $elem->id }}" type="number" min="1" step="1" value="{{ $elem->quantity }}">
                  </div>
                  <div class="col s3 m2"><a onclick="updateQuantity({{ $elem->id }})" class="deep-orange waves-effect waves-light btn "><i class="material-icons">refresh</i></a></div>
                  <div class="col s3 m2 right-align" style="margin-top: 8px">{{ $elem->price }}&euro;</div>
                  <div class="col s3 m2 right-align"><a onclick="removeFromCart({{ $elem->id }})" class="btn-flat"><i class="material-icons">delete</i></a></div>
              </div>
              @empty
              <div class="row center card-panel">
                <h5>Il tuo carrello è vuoto!</h5>
              </div>
              @endforelse
            </div>
            <div class="col s12 l4">
              <div class="card">
                <div class="card-content" >
                  <table>
                    <thead>
                      <h5 class="center">Riepilogo</h5>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Subtotale</td>
                        <td id="subtot">
                          <div class="right-align">{{ Cart::session(Auth::id())->getSubTotal() }}&euro;</div>
                        </td>
                      </tr>
                      <tr>
                        <td>Spese di spedizione</td>
                        <td>
                          <div class="right-align">Gratis</div>
                        </td>
                      </tr>
                      <tr>
                        <td>Totale</td>
                        <td id=tot>
                          <div class="right-align">{{ Cart::session(Auth::id())->getTotal() }}&euro;</div>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <div class="input-field">
                            <input id="date" type="text" class="datepicker">
                            <label for="date">Giorno di consegna</label>
                            @error('date')
                            <span>{{ $message }}</span>
                            @enderror
                          </div>
                        </td>
                        <td>
                          <div class="input-field">
                            <input id="time" type="text" class="timepicker">
                            <label for="time">Ora di consegna</label>
                            @error('time')
                            <span>{{ $message }}</span>
                            @enderror
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <a href="{{ url('client/home') }}" class="btn-flat waves-effect">Indietro</a>
                        </td>
                        <td>
                          @if(Cart::session(Auth::id())->isEmpty())
                          <a id="send_order" class="btn waves-effect waves-light hoverable deep-orange disabled" type="submit" name="action" onclick="sendOrder()">Checkout<i class="material-icons right">send</i></a>
                          @else
                          <a id="send_order" class="btn waves-effect waves-light hoverable deep-orange" type="submit" name="action" onclick="sendOrder()">Checkout<i class="material-icons right">send</i></a>
                          @endif
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript" src="{{ asset('js/clienthome.js') }}"></script>
<script>
  function removeFromCart(product_id) {
    var req = new HttpClient();
    req.get("{{ url('client/cart/remove') }}?product_id=" + product_id, function(response) {
      var cart_qty = document.getElementById('cart_qty')
      var subtot = document.getElementById('subtot')
      var tot = document.getElementById('tot')
      var row = document.getElementById('row-' + product_id)
      row.parentNode.removeChild(row)
      var res_parsed = JSON.parse(response)
      cart_qty.textContent = res_parsed.cart_qty
      subtot.textContent = res_parsed.stot + '\u20AC'
      tot.textContent = res_parsed.tot + '\u20AC'
    });
  }

  function updateQuantity(product_id) {
    var quantity = document.getElementById('new_quantity_' + product_id).value
    var req = new HttpClient();
    req.get("{{ url('client/cart/update') }}?product_id=" + product_id +"&quantity=" + quantity, function(response) {
      var cart_qty = document.getElementById('cart_qty')
      var subtot = document.getElementById('subtot')
      var tot = document.getElementById('tot')
      var row = document.getElementById('row-' + product_id)
      var res_parsed = JSON.parse(response)
      cart_qty.textContent = res_parsed.cart_qty
      subtot.textContent = res_parsed.stot + '\u20AC'
      tot.textContent = res_parsed.tot + '\u20AC'
    });
  }

  function sendOrder() {
    var m_date = document.getElementById('date').value
    var time = document.getElementById('time').value
    location.href = '{{ url('client/payment') }}' + '?date=' + m_date + '&time=' + time
  }
</script>
@endsection

resources/views/client/home.blade.php
@extends('layouts.app')

@section('nav')
@include('includes.nav')
@endsection

@section('content')

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <div class="row">
      <ul class="tabs tabs-fixed-width tab-demo z-depth-1">
        @foreach($types as $type)
        @switch($type)
        @case('appetizer')
        <li class="tab"><a href="#{{ $type }}">Antipasti</a></li>
        @break
        @case('first')
        <li class="tab"><a href="#{{ $type }}">Primi</a></li>
        @break
        @case('second')
        <li class="tab"><a href="#{{ $type }}">Secondi</a></li>
        @break
        @case('salad')
        <li class="tab"><a href="#{{ $type }}">Insalate</a></li>
        @break
        @case('dessert')
        <li class="tab"><a href="#{{ $type }}">Dolci</a></li>
        @break
        @case('drink')
        <li class="tab"><a href="#{{ $type }}">Bevande</a></li>
        @break
        @endswitch
        @endforeach
      </ul>
      <div class="section no-pad-bot" id="index-banner">
        @foreach($types as $type)
        <div id="{{ $type }}" class="col s12 cards-container">
          @foreach($products as $product)
          @if($product->type == $type)
          <div class="card hoverable">
            <div class="card-image">
              @if($product->image != null)
                <img src="{{ Storage::url($product->image) }}" alt="" class="activator responsive-img">
              @else
                <img src="https://s3-eu-west-1.amazonaws.com/unistation/placeholders/imageprofile-placeholder-350x350.png" alt="" class="activator circle responsive-img">
              @endif
              <a id="add_btn" onclick="addToCart({{ $product->id }})" class="btn-floating halfway-fab waves-effect waves-light red hoverable"><i class="material-icons">add_shopping_cart</i></a>
            </div>
            <div class="card-content" >
              <span class="card-title activator"><i class="material-icons left">expand_less</i>{{ $product->name }}</span>
              <p class="right-align">{{ $product->price }}&euro;</p>
            </div>
            <div class="card-reveal">
              <div class=" row center">
              <span class="card-title left-align grey-text text-darken-4">{{ $product->vendor->name }}<i class="material-icons right">close</i></span>
              </div> 
              <div class="row center">
              @if($product->vendor->image != null)
                <img src="{{ Storage::url($product->vendor->image) }}" alt="" class="activator circle responsive-img" style="width: 100px; height: 100px;">
              @else
                <img src="https://s3-eu-west-1.amazonaws.com/unistation/placeholders/imageprofile-placeholder-350x350.png" alt="" class="activator circle responsive-img">
              @endif
            </div>
              <p class="material-icons center">
                @for ($i = 1; $i <= $product->vendor->rating; $i++)
                    grade
                @endfor
                @for (; $i <= 5; $i++)
                    star_border
                @endfor
              </p>
            </div>
          </div>
          @endif
          @endforeach
        </div>
        @endforeach
      </div>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('js/clienthome.js') }}"></script>
<script>
  function addToCart(product_id) {
    var req = new HttpClient()
    req.get("{{ url('client/cart/add') }}?product_id=" + product_id, function(response) {
      var cart_qty = document.getElementById('cart_qty')
      if (cart_qty.style.display === 'none') {
        cart_qty.style.display = 'block'
      }
      var res_parsed = JSON.parse(response)
      console.log(res_parsed.cart_qty)
      cart_qty.textContent = res_parsed.cart_qty
      M.toast({html: 'Prodotto aggiunto', classes: 'rounded'})
    })
  }
</script>
@endsection

resources/views/client/orders.blade.php
@extends('layouts.app')

@section('nav')
@include('includes.nav')
@endsection

@section('content')
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
        <div class="col s12">
          <div class="row">
            <div class="card">
              <div class="card-content" >
                <div class="row">
                  <div class="col s5">
                    <a href="{{ url('client/home') }}" class="btn-flat waves-effect ">Indietro</a>
                  </div>
                  <div class="col s7">
                      <h5 class="">I tuoi ordini</h5>
                    </div>
                </div>
                <table class="centered order-table">
                  <thead>
                    <tr>
                      <th>Numero ordine</th>
                      <th>Data</th>
                      <th>Prezzo totale</th>
                      <th>Stato ordine</th>
                      <th>Feedback</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($orders as $order)
                    <form action="{{url('client/orders', [$order->id])}}" method="POST">
                      @method('patch')
                      @csrf
                      <tr>
                        @php
                          $date = Carbon::parse($order->created_at);
                        @endphp
                        <td data-label="product_order">#{{ $order->id }}</td>
                        <td data-label="date">{{ $date->day }} {{ $date->locale('it')->monthName }} {{ $date->year }}</td>
                        <td data-label="total">{{ $order->total }} &euro;</td>
                        <td data-label="order_state">
                          @if($order->delivered == true)
                          Spedito
                          @else
                          <b>In preaparazione</b>
                          @endif
                        </td>
                        <td data-label="feedback">
                          <!-- Modal Trigger -->
                          <a class="waves-effect waves-light deep-orange btn modal-trigger
                              @if($order->feedback)
                                disabled 
                              @endif"
                              href="#modal{{$order->id}}">
                              <i class="material-icons">grade</i>
                          </a>
                        </td>
                      </tr>
                      <!-- Modal Structure -->
                      <div id="modal{{$order->id}}" class="modal">
                        <div class="modal-content">
                          <h4>Come valuti il servizio?</h4>
                          <div>
                          @for ($i = 1; $i <= 5; $i++)
                            <i class="material-icons rate" onmouseover = "fillStar(this)">star_border</i>
                          @endfor
                          </div>
                        </div>
                        <div class="modal-footer">
                          <button class="modal-close waves-effect waves-green btn-flat" type="submit">Invia</a>
                        </div>
                      </div>
                    </form>
                    @empty
                    <tr>
                      <td colspan='5'><h5>Non ci sono ancora ordini!<h5></td>
                    </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript" src="{{ asset('js/clienthome.js') }}"></script>
@endsection

resources/views/client/payment.blade.php
@extends('layouts.app')

@section('nav')
@include('includes.nav')
@endsection

@section('content')
<div class="valign-wrapper row register-box">
  <div class="col card hoverable s10 pull-s1 m6 pull-m3 l4 pull-l4">
    <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{{ url('client/payment/confirm_order') }}">
      @csrf
      <div class="card-content">
        <span class="card-title">Completa Ordine</span>
        <div class="row">
          <div class="input-field col s12">
            <div  class="col s4">
              <label class="radio-inline">
                <input name="group1" type="radio" checked />
                <span><i class=" fab fa-cc-mastercard fa-2x"></i></span> 
              </label>
            </div>
            <div  class="col s4">
              <label class="radio-inline">
                <input name="group1" type="radio" />
                <span><i class="fab fa-cc-visa fa-2x"></i></span>
              </label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <label for="client_name">Intestatario</label>
            <input type="text" class="validate" name="client_name" id="client_name" value=""/>
            @error('client_name')
            <span>{{ $message }}</span>
            @enderror
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6">
            <label for="card_number">Numero carta</label>
            <input type="text" class="validate" name="card_number" id="card_number" value=""/>
            @error('card_number')
            <span>{{ $message }}</span>
            @enderror
          </div>
          <div class="input-field col s6">
            <input name="cvv" id="cvv" type="text" class="validate" >
            <label for="cvv">CVV</label>
            @error('cvv')
            <span>{{ $message }}</span>
            @enderror
          </div>
        </div>
        <div class="row">
          <div class="col-sm-2">
            <div class="input-field col s6">
              <input name="expiration_month" id="expiration_month" type="number" class="validate" value="">
              <label for="expiration_month">Mese scadenza</label>
              @error('expiration_month')
              <span>{{ $message }}</span>
              @enderror
            </div>
          </div>
          <div class="input-field col s6">
            <input name="expiration_year" id="expiration_year" type="number" class="validate" value="">
            <label for="expiration_year">Anno scadenza</label>
            @error('expiration_year')
            <span>{{ $message }}</span>
            @enderror
          </div>
        </div>
        <div class="row">
          <div class="col s12 right-align">
            <h5>Totale: {{ Cart::getTotal() }}&euro;</h5>
          </div>
        </div>
      </div>
      <input type="hidden" id="date" name="date" value="">
      <input type="hidden" id="time" name="time" value="">
      <div class="row card-action">
        <div class="left-align col s6">
          <a href="{{ url('client/cart') }}" class="btn-flat waves-effect waves-light">Indietro</a>
        </div>
        <div class="right-align col s6">
          <button type="submit" class="btn deep-orange waves-effect waves-light hoverable">Paga Ora</button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript" src="{{ asset('js/clienthome.js') }}"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var url = new URL(window.location.href)
  var m_date = url.searchParams.get('date')
  var time = url.searchParams.get('time')

  var c_date = document.getElementById('date')
  var c_time = document.getElementById('time')

  c_time.value = time
  c_date.value = m_date
});
</script>
@endsection

resources/views/client/settings.blade.php
@extends('layouts.app')

@section('nav')
@include('includes.nav')
@endsection

@section('content')
  <div class="valign-wrapper row register-box">
    <div class="col card hoverable s10 pull-s1 m6 pull-m3 l4 pull-l4">
      <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{{ route('client-edit.update', Auth::id()) }}">
        @csrf
        @method('PATCH')
        <div class="card-content">
          <div class="row center">
                <span class="card-title">Modifica il tuo profilo</span>
          </div>
          <div class="row center user-view">
            <a>
              <img src="{{ Storage::url(Auth::user()->image) }}" alt="" class="circle responsive-img" style="width: 100px; height: 100px;">
            </a>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <label for="client_name">Nome</label>
              <input type="text" class="validate" name="client_name" id="client_name" value="{{ Auth::user()->name }}"/>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <label for="client_surname">Cognome</label>
              <input type="text" class="validate" name="client_surname" id="client_surname" value="{{ Auth::user()->surname }}"/>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <label for="client_email">Email</label>
              <input type="email" class="validate" name="client_email" id="client_email" value="{{ Auth::user()->email }}"/>
            </div>
          </div>
          <div class="row">
            <div class="file-field input-field">
              <div class="btn deep-orange">
                <span>File</span>
                <input name="newavatar" type="file">
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text" placeholder="Carica avatar">
              </div>
            </div>
          </div>
        </div>
        <div class="card-action right-align">
          <button type="submit" class="btn deep-orange waves-effect waves-light">Aggiorna</button>
        </div>
      </form>
    </div>
  </div>
@endsection
@section('scripts')
<script type="text/javascript" src="{{ asset('js/clienthome.js') }}"></script>
@endsection